service: default
runtime: python27
api_version: 1
threadsafe: true

# https://cloud.google.com/appengine/docs/standard/python/config/appref#automatic_scaling
basic_scaling:
  max_instances: 1
  idle_timeout: 5m

handlers:
- url: /.*
  script: run.app

skip_files:
- node_modules
- public
- src
- venv
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
